# Generated by Django 2.2.1 on 2019-05-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question',
            new_name='question_id',
        ),
    ]
